name: Deploy Docker Compose to Remote Server

on:
  push:
    branches:
      - main   # O la rama que prefieras

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Check out el código del repositorio
    - name: Checkout Repository
      uses: actions/checkout@v3

    # 2. Configurar SSH para acceder al servidor remoto
    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    # 3. Conectar al servidor remoto y desplegar Docker Compose
    - name: Deploy to Server
      run: |
        ssh -o StrictHostKeyChecking=no username@${{ secrets.SERVER_IP }} << 'EOF'
          cd /ruta/del/proyecto
          git pull origin main
          docker-compose down
          docker-compose up -d
        EOF
